// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    each: function(arr, fn) {
      var i, item, len, results;
      if (arr == null) {
        arr = [];
      }
      results = [];
      for (i = 0, len = arr.length; i < len; i++) {
        item = arr[i];
        results.push(fn(item));
      }
      return results;
    },
    filter: function(arr, fn) {
      var i, item, len, results, tmp;
      if (arr == null) {
        arr = [];
      }
      tmp = [];
      results = [];
      for (i = 0, len = arr.length; i < len; i++) {
        item = arr[i];
        if (fn(item)) {
          results.push(tmp.push(item));
        } else {
          results.push(void 0);
        }
      }
      return results;
    },
    unique: function(arr, fn) {
      var i, item, len, map, ret, tmp;
      if (arr == null) {
        arr = [];
      }
      map = {};
      tmp = [];
      for (i = 0, len = arr.length; i < len; i++) {
        item = arr[i];
        if (fn) {
          ret = fn(item);
        } else {
          ret = item;
        }
        if (map[ret]) {
          continue;
        } else {
          tmp.push(ret);
          map[ret] = true;
        }
      }
      return tmp;
    },
    keys: function(obj) {
      var k, tmp, v;
      tmp = [];
      for (k in obj) {
        v = obj[k];
        tmp.push(k);
      }
      return tmp;
    }
  };

}).call(this);

//# sourceMappingURL=util.js.map
